"""agregar_nuevo_modelo

Revision ID: c66cd0ac1387
Revises: eaa12dde0779
Create Date: 2025-11-25 18:46:29.710209+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66cd0ac1387'
down_revision: Union[str, Sequence[str], None] = 'eaa12dde0779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
